name: cnn_rl
channels:
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  - python=3.9.21
  - pip=25.0
  - numpy=1.26.4
  - scipy=1.13.1
  - pandas=2.2.3
  - matplotlib=3.9.4
  - scikit-learn=1.6.1
  - opencv-python=4.11.0.86
  - pytorch=2.5.1
  - torchvision=0.20.1
  - torchaudio=2.5.1
  - pytorch-cuda=12.4
  - stable-baselines3=2.5.0
  - gymnasium=1.0.0
  - tqdm=4.67.1
  - tensorboard=2.19.0
  - pip:
      - wandb==0.19.6
      - absl-py==2.1.0
      - cloudpickle==3.1.1
      - gymnasium==1.0.0
      - pygame==2.6.1
